In [4]:
import os
os.environ['SM_FRAMEWORK'] = 'tf.keras'

import segmentation_models as sm

model = sm.Unet(
    backbone_name='resnet34', 
    encoder_weights='imagenet', 
    input_shape=(256, 256, 3), 
    classes=1, 
    activation='sigmoid'
)


Segmentation Models: using `tf.keras` framework.
85521592/85521592 ━━━━━━━━━━━━━━━━━━━━ 27s 0us/step


In [5]:
import segmentation_models_pytorch as smp

model = smp.Unet(
    encoder_name="resnet34",        # choose encoder, e.g. mobilenet_v2 or efficientnet-b7
    encoder_weights="imagenet",     # use `imagenet` pre-trained weights for encoder initialization
    in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
    classes=3,                      # model output channels (number of classes in your dataset)
)

d:\Projects\VsCode\Python\img_processing_system\.conda\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
d:\Projects\VsCode\Python\img_processing_system\.conda\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\31204\.cache\huggingface\hub\models--smp-hub--resnet34.imagenet. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as a

In [ ]:
import torch
a = torch.randn(4, 4)
print(a)
torch.argmax(a, dim=1) # 每一行最大元素的下标

tensor([[-0.0931,  1.2765, -0.6405, -0.2433],
        [-0.7287,  0.0699,  1.0226, -0.0151],
        [-1.4360,  0.2025,  1.2713, -0.8034],
        [ 0.9247, -0.2536,  0.5500,  0.8789]])


tensor([1, 2, 2, 0])

In [ ]:
torch.argmax(a, dim=0) # 每一列最大元素的下标

tensor([1, 0, 1, 0])

In [ ]:
a = torch.randn(4, 4, 4)
print(a)
torch.argmax(a, dim=1) # 输出4个二维矩阵的每一列最大元素的下标

tensor([[[-0.0489,  0.3053,  0.0528, -0.4225],
         [ 0.0300,  0.6682, -1.2099, -0.6489],
         [ 0.2906,  2.0094, -0.1708,  0.0365],
         [-0.8599, -0.3847,  1.8094, -1.1798]],

        [[ 0.9542,  1.6088, -0.3205,  0.4684],
         [ 0.1263,  1.1628,  0.6352, -0.1534],
         [-0.1892, -2.1707,  1.3857,  0.3710],
         [ 0.0046, -0.5479,  1.2225, -1.2072]],

        [[-1.1979, -0.2986, -0.2680, -0.0538],
         [ 0.8723,  0.9237, -1.5431,  1.4367],
         [-1.1248,  1.1123,  0.3210,  0.9656],
         [ 0.3047,  0.6460, -0.1760, -0.1512]],

        [[-0.3018, -0.3333,  0.3686,  0.4925],
         [ 0.0789, -0.6327,  0.1999,  0.2238],
         [-0.6470,  0.5958, -0.4412, -0.6201],
         [-0.1424, -0.3006,  1.3116,  0.5466]]])


tensor([[2, 2, 3, 2],
        [0, 0, 2, 0],
        [1, 2, 2, 1],
        [1, 2, 3, 3]])

In [12]:
a = torch.randn(1, 6, 4, 2)
print(a)
res= torch.argmax(a, dim=1)

tensor([[[[ 1.9538, -0.1935],
          [-0.6071,  0.5476],
          [ 1.3069,  0.2146],
          [-0.3215, -0.2366]],

         [[ 0.3055, -0.0743],
          [-0.3948,  0.7013],
          [-0.2386,  1.9177],
          [-0.0576,  1.2706]],

         [[-1.3504,  1.0515],
          [ 1.0404, -0.7795],
          [ 0.3519, -0.7342],
          [-0.5096, -1.4420]],

         [[ 0.2416,  0.1613],
          [ 0.3926, -0.5801],
          [-0.1186,  1.6841],
          [-1.0797,  1.1324]],

         [[-0.6027, -1.6150],
          [-1.3041, -0.5325],
          [ 0.0332,  0.3823],
          [ 0.4094, -0.0813]],

         [[-0.0128,  0.2293],
          [ 2.0436, -0.8405],
          [-0.2364, -0.0740],
          [-0.5844, -0.3534]]]])


In [13]:
print(res.shape)

torch.Size([1, 4, 2])
